import keyMirror from 'keymirror'

export default keyMirror({
  LOADING: null,
  LOADED: null,
  ERROR: null,

  GET_TODOS_REQUEST: null,
  GET_TODOS_SUCCESS: null,

  ADD_TODO_REQUEST: null,
  ADD_TODO_SUCCESS: null,

  SET_VISIBILITY_FILTER: null,

  TOGGLE_ALL_TODO_REQUEST: null,
  TOGGLE_ALL_TODO_SUCCESS: null,

  TOGGLE_TODO_REQUEST: null,
  TOGGLE_TODO_SUCCESS: null,

  DELETE_TODO_REQUEST: null,
  DELETE_TODO_SUCCESS: null,

  DELETE_ALL_TODO_REQUEST: null,
  DELETE_ALL_TODO_SUCCESS: null,

  DELETE_ALL_COMPLETED_TODO_REQUEST: null,
  DELETE_ALL_COMPLETED_TODO_SUCCESS: null,
})
