import keyMirror from 'keymirror'

export default keyMirror({
  LOADING: null,
  LOADED: null,
  ERROR: null,
  SHOW_CONGRATS: null,
  HIDE_CONGRATS: null,

  GET_TODOS_REQUEST: null,
  GET_TODOS_SUCCESS: null,

  ADD_TODO_REQUEST: null,
  ADD_TODO_BATCH_REQUEST: null,
  ADD_TODO_SUCCESS: null,

  SET_VISIBILITY_FILTER: null,

  TOGGLE_ALL_TODO_REQUEST: null,
  TOGGLE_ALL_TODO_SUCCESS: null,

  TOGGLE_TODO_REQUEST: null,
  TOGGLE_TODO_SUCCESS: null,

  DELETE_TODO_REQUEST: null,
  DELETE_TODO_SUCCESS: null,

  DELETE_ALL_TODO_REQUEST: null,
  DELETE_ALL_TODO_SUCCESS: null,

  DELETE_ALL_COMPLETED_TODO_REQUEST: null,
  DELETE_ALL_COMPLETED_TODO_SUCCESS: null,

  START_SYNC: null,
  STOP_SYNC: null,
  SYNC_CANCELLED: null,
  SYNC_FAILED: null,
  SYNC_FINISHED: null,

  START_BG_SYNC: null,
  SET_BG_SYNC_PROGRESS: null,
  CANCEL_BG_SYNC: null,
  BG_SYNC_DONE: null,
  BG_SYNC_CANCELLED: null,
  BG_SYNC_FAILED: null,
})
